// ==============================
// CONFIGURACIÓN: TUS PRODUCTOS
// ==============================
// Modifica este array para añadir / quitar / editar productos.
// Solo tú, editando este archivo, puedes cambiar el catálogo.
const PRODUCTS = [
    // ROPA - MUJER (Continuación)
    {
        id: 9,
        nombre: "Conjunto de Pijama Satinado LuxeNights Talla L",
        categoria: "Ropa",
        subcategoria: "Pijamas",
        genero: "mujer",
        precio: 13.00,
        descripcion: "Conjunto de Pijama Satinado LuxeNights, Set de Lencería para Dormir. Disponible en 3 elegantes colores: Rosa vibrante, Beige suave y Malva. Talla L.",
        imagen: "images/pijama_satin_1.jpg",
        imagenes: ["images/pijama_satin_1.jpg", "images/pijama_satin_2.jpg", "images/pijama_satin_3.jpg", "images/pijama_satin_4.jpg"],
        tallas: ["L"],
        colores: ["Rosa", "Beige", "Malva"],
        estilos: ["Elegante", "Lencería", "Noche"],
        disponible: true,
    },

    // ============================
    // PREMIUM - MARCAS PREMIUM
    // ============================
    {
        id: 14,
        nombre: "Top sin Mangas Ajustado - 4 Diseños Talla L",
        categoria: "Ropa",
        subcategoria: "Tops",
        genero: "mujer",
        precio: 5.00,
        descripcion: "Top sin mangas ajustado, disponible en 4 colores: negro sólido con lazo, gris, rayas blancas y negras, y blanco con estampado de cerezas. Perfecto para verano, vacaciones y la playa.",
        imagen: "images/top_rayas_3.png",
        imagenes: ["images/top_rayas_1.png", "images/top_rayas_2.png", "images/top_rayas_3.png"],
        tallas: ["L"],
        colores: ["Negro con Lazo", "Gris", "Rayas Blancas y Negras", "Blanco Cherry"],
        estilos: ["Verano", "Casual", "Playa"],
        disponible: true,
    },
    {
        id: 15,
        nombre: "Top sin mangas (Blusa) 4 Diseños Talla L",
        categoria: "Ropa",
        subcategoria: "Tops",
        genero: "mujer",
        precio: 5.00,
        descripcion: "Top sin mangas ajustado, disponible en 4 diseños: leopardo, gris, rayas blancas y negras, y negro sólido. Perfecto para uso casual y verano.",
        imagen: "images/top_4disenos_1.jpg",
        imagenes: ["images/top_4disenos_1.jpg", "images/top_4disenos_2.jpg", "images/top_4disenos_3.png", "images/top_4disenos_4.jpg", "images/top_4disenos_5.jpg"],
        tallas: ["L"],
        colores: ["Leopardo", "Gris", "Rayas Blancas y Negras", "Negro Sólido"],
        estilos: ["Casual", "Verano", "Básico"],
        disponible: true,
    },
    {
        id: 16,
        nombre: "Camiseta sin Mangas con Bordado de Lazos Talla L",
        categoria: "Ropa",
        subcategoria: "Camisetas",
        genero: "mujer",
        precio: 5.00,
        descripcion: "Camiseta sin mangas de escote redondo con bordado de lazo para mujeres. Disponible en 3 colores: Rosa Intenso, Rosa Claro y Blanco. Perfecta para uso casual y diario.",
        imagen: "images/camiseta_lazos_1.jpg",
        imagenes: ["images/camiseta_lazos_1.jpg", "images/camiseta_lazos_2.jpg", "images/camiseta_lazos_3.jpg", "images/camiseta_lazos_4.jpg", "images/camiseta_lazos_5.jpg"],
        tallas: ["L"],
        colores: ["Rosa Intenso", "Rosa Claro", "Blanco"],
        estilos: ["Casual", "Básico", "Diario"],
        disponible: true,
    },
    {
        id: 17,
        nombre: "Set de Pijama con Estampado de Caricatura Talla L",
        categoria: "Ropa",
        subcategoria: "Pijamas",
        genero: "mujer",
        precio: 7.00,
        descripcion: "Set de Pijama con Estampado de Caricatura: Camiseta de Tirantes y Pantalones Cortos. Disponible en varios diseños adorables: Corazón, Osito, Moño y Lazos.",
        imagen: "images/pijama_caricatura_1.jpg",
        imagenes: ["images/pijama_caricatura_1.jpg", "images/pijama_caricatura_2.jpg", "images/pijama_caricatura_3.jpg", "images/pijama_caricatura_4.jpg"],
        tallas: ["L"],
        colores: ["Beige", "Rojo", "Negro", "Rosa"],
        estilos: ["Pijama", "Verano", "Cómodo"],
        disponible: true,
    },
    {
        id: 18,
        nombre: "Set de Pijama con Estampado de Caricatura (Aguacate) Talla M",
        categoria: "Ropa",
        subcategoria: "Pijamas",
        genero: "mujer",
        precio: 7.00,
        descripcion: "Set de Pijama con Estampado de Caricatura: Camiseta de Tirantes y Pantalones Cortos. Diseños divertidos: Aguacate, Osito Rosa, Leopardo y Negro 'Honey'.",
        imagen: "images/pijama_aguacate_1.jpg",
        imagenes: ["images/pijama_aguacate_1.jpg", "images/pijama_aguacate_2.jpg", "images/pijama_aguacate_3.jpg", "images/pijama_aguacate_4.jpg"],
        tallas: ["M"],
        colores: ["Blanco/Aguacate", "Negro/Osito", "Negro/Leopardo"],
        estilos: ["Pijama", "Verano", "Divertido"],
        disponible: true,
    },
    {
        id: 19,
        nombre: "Set de Pijama con Estampado de Fresas Talla S",
        categoria: "Ropa",
        subcategoria: "Pijamas",
        genero: "mujer",
        precio: 7.00,
        descripcion: "Set de Pijama con Estampado de Fresas: Camiseta de Tirantes y Pantalones Cortos con lazo. Disponible en 3 colores: Negro, Rosa y Blanco.",
        imagen: "images/pijama_fresas_1.jpg",
        imagenes: ["images/pijama_fresas_1.jpg", "images/pijama_fresas_2.jpg", "images/pijama_fresas_3.jpg", "images/pijama_fresas_4.jpg"],
        tallas: ["S", "M", "L"],
        colores: ["Negro", "Rosa", "Blanco"],
        estilos: ["Pijama", "Verano", "Cute"],
        disponible: true,
    },
    {
        id: 20,
        nombre: "Set de Pijama Casual de Canalé Talla L",
        categoria: "Ropa",
        subcategoria: "Pijamas",
        genero: "mujer",
        precio: 9.00,
        descripcion: "Set de Pijama Casual de tejido canalé (ribbed) suave. Camiseta de tirantes con detalle de lazo y pantalones cortos con borde ondulado. Disponible en Lila, Beige y Verde Menta.",
        imagen: "images/pijama_casual_1.jpg",
        imagenes: ["images/pijama_casual_1.jpg", "images/pijama_casual_2.jpg", "images/pijama_casual_3.jpg", "images/pijama_casual_4.jpg", "images/pijama_casual_5.jpg"],
        tallas: ["L"],
        colores: ["Lila", "Beige", "Verde Menta"],
        estilos: ["Casual", "Cómodo", "Básico"],
        disponible: true,
    },
    {
        id: 21,
        nombre: "Pullover con Diseño de Corazón/Love Talla M",
        categoria: "Ropa",
        subcategoria: "Tops",
        genero: "mujer",
        precio: 6.00,
        descripcion: "Pullover casual de manga corta con estampados románticos de corazón y texto 'Love'. Disponible en 3 colores: Negro, Rojo y Blanco. Tela suave y cómoda.",
        imagen: "images/pullover_love_1.png",
        imagenes: ["images/pullover_love_1.png", "images/pullover_love_2.png", "images/pullover_love_3.png", "images/pullover_love_4.png", "images/pullover_love_5.png"],
        tallas: ["M"],
        colores: ["Negro", "Rojo", "Blanco"],
        estilos: ["Casual", "Romántico", "Diario"],
        disponible: true,
    },
    {
        id: 22,
        nombre: "Set de Ropa Interior Informal (Top Tubo + Shorts) - Rojo Vino Talla L",
        categoria: "Ropa",
        subcategoria: "Lencería",
        genero: "mujer",
        precio: 10.00,
        descripcion: "Set de dos piezas informal y cómodo. Incluye top tipo tubo sin tirantes y shorts ajustados con textura a cuadros. Ideal para estar en casa o uso casual.",
        imagen: "images/ropa_interior_informal_1.png",
        imagenes: ["images/ropa_interior_informal_1.png", "images/ropa_interior_informal_2.png", "images/ropa_interior_informal_3.jpg"],
        tallas: ["L"],
        colores: ["Rojo Vino"],
        estilos: ["Casual", "Sexy", "Cómodo"],
        disponible: true,
    },
    {
        id: 23,
        nombre: "Set de Ropa Interior Informal (Top Tubo + Shorts) - Carmelita Talla M",
        categoria: "Ropa",
        subcategoria: "Lencería",
        genero: "mujer",
        precio: 10.00,
        descripcion: "Set de dos piezas informal y cómodo. Incluye top tipo tubo sin tirantes y shorts ajustados con textura a cuadros. Ideal para estar en casa o uso casual.",
        imagen: "images/ropa_interior_carmelita_1.png",
        imagenes: ["images/ropa_interior_carmelita_1.png", "images/ropa_interior_carmelita_2.png", "images/ropa_interior_carmelita_3.png"],
        tallas: ["M"],
        colores: ["Carmelita"],
        estilos: ["Casual", "Sexy", "Cómodo"],
        disponible: true,
    },
    {
        id: 24,
        nombre: "Set de Lencería Sexy (Corazones) Talla S",
        categoria: "Ropa",
        subcategoria: "Lencería",
        genero: "mujer",
        precio: 8.00,
        descripcion: "Set de lencería sexy de dos piezas en blanco con detalles de encaje rojo y estampado de corazones. Incluye sujetador y tanga a juego.",
        imagen: "images/lenceria_corazones_1.png",
        imagenes: ["images/lenceria_corazones_1.png", "images/lenceria_corazones_2.png", "images/lenceria_corazones_3.png"],
        tallas: ["S"],
        colores: ["Blanco/Rojo"],
        estilos: ["Sexy", "Romántico", "Lencería"],
        disponible: true,
    },
    {
        id: 25,
        nombre: "Set de Lencería Sexy (Leopardo) Talla L",
        categoria: "Ropa",
        subcategoria: "Lencería",
        genero: "mujer",
        precio: 8.00,
        descripcion: "Set de lencería sexy de dos piezas con estampado de leopardo y detalles de encaje negro. Incluye sujetador y tanga a juego.",
        imagen: "images/lenceria_leopardo_1.png",
        imagenes: ["images/lenceria_leopardo_1.png", "images/lenceria_leopardo_2.png", "images/lenceria_leopardo_3.png"],
        tallas: ["L"],
        colores: ["Leopardo"],
        estilos: ["Sexy", "Salvaje", "Lencería"],
        disponible: true,
    },
    {
        id: 26,
        nombre: "Conjunto Deportivo 'Sweet' (2 Piezas) - Rojo Talla L",
        categoria: "Ropa",
        subcategoria: "Conjuntos",
        genero: "mujer",
        precio: 10.00,
        descripcion: "Conjunto de 2 piezas: sujetador deportivo con letra estampada 'Sweet' y costuras a contraste. Alta elasticidad y muy cómodo. Ideal para entrenamiento o uso casual.",
        imagen: "images/conjunto_sweet_1.jpg",
        imagenes: ["images/conjunto_sweet_1.jpg", "images/conjunto_sweet_2.png", "images/conjunto_sweet_3.jpg", "images/conjunto_sweet_4.jpg"],
        tallas: ["L"],
        colores: ["Vino"],
        estilos: ["Deportivo", "Casual", "Cómodo"],
        disponible: true,
    },
    {
        id: 27,
        nombre: "Conjunto Deportivo 'Sweet' (2 Piezas) - Naranja Talla XL",
        categoria: "Ropa",
        subcategoria: "Conjuntos",
        genero: "mujer",
        precio: 10.00,
        descripcion: "Conjunto de 2 piezas: sujetador deportivo con letra estampada 'Sweet' y costuras a contraste. Alta elasticidad y muy cómodo. Ideal para entrenamiento o uso casual.",
        imagen: "images/conjunto_sweet_naranja_1.png",
        imagenes: ["images/conjunto_sweet_naranja_1.png", "images/conjunto_sweet_naranja_2.png", "images/conjunto_sweet_naranja_3.jpg", "images/conjunto_sweet_naranja_4.png"],
        tallas: ["XL"],
        colores: ["Naranja"],
        estilos: ["Deportivo", "Casual", "Cómodo"],
        disponible: true,
    },
];

