// ==============================
// CONFIGURACIÓN: WHATSAPP
// ==============================
// Cambia este número por tu número de WhatsApp (formato internacional sin +)
// Ejemplo: para Cuba +53 5XXXXXXX sería "535XXXXXXX"
const WHATSAPP_NUMBER = "5353056794"; // ⚠️ CAMBIAR POR TU NÚMERO REAL

// ==============================
// CONFIGURACIÓN: TUS PRODUCTOS
// ==============================
// Modifica este array para añadir / quitar / editar productos.
// Solo tú, editando este archivo, puedes cambiar el catálogo.
const PRODUCTS = [
    // ROPA - MUJER (Continuación)
    {
        id: 9,
        nombre: "Conjunto de pijama satinado LuxeNights - Talla L",
        categoria: "Ropa",
        subcategoria: "Pijamas",
        genero: "mujer",
        precio: 13.00,
        descripcion: "Conjunto de Pijama Satinado LuxeNights, Set de Lencería para Dormir. Disponible en 3 elegantes colores: Rosa vibrante, Beige suave y Malva.",
        imagen: "images/pijama_satin_1.jpg",
        imagenes: ["images/pijama_satin_1.jpg", "images/pijama_satin_2.jpg", "images/pijama_satin_3.jpg", "images/pijama_satin_4.jpg"],
        tallas: ["L"],
        colores: ["Rosa", "Beige", "Malva"],
        estilos: ["Elegante", "Lencería", "Noche"],
        disponible: true,
    },

    // ============================
    // PREMIUM - MARCAS PREMIUM
    // ============================
    {
        id: 14,
        nombre: "Top sin mangas ajustado 4 Diseños (🍒) - Talla L",
        categoria: "Ropa",
        subcategoria: "Tops",
        genero: "mujer",
        precio: 5.00,
        descripcion: "Top sin mangas ajustado, disponible en 4 colores: negro sólido con lazo, gris, rayas blancas y negras, y blanco con estampado de cerezas. Perfecto para verano, vacaciones y la playa.",
        imagen: "images/top_rayas_3.png",
        imagenes: ["images/top_rayas_1.png", "images/top_rayas_2.png", "images/top_rayas_3.png"],
        tallas: ["L"],
        colores: ["Negro con Lazo", "Gris", "Rayas Blancas y Negras", "Blanco Cherry"],
        estilos: ["Verano", "Casual", "Playa"],
        disponible: true,
    },
    {
        id: 15,
        nombre: "Top sin mangas ajustados en 4 diseños (🐆) - Talla L",
        categoria: "Ropa",
        subcategoria: "Tops",
        genero: "mujer",
        precio: 5.00,
        descripcion: "Top sin mangas ajustado, disponible en 4 diseños: leopardo, gris, rayas blancas y negras, y negro sólido. Perfecto para uso casual y verano.",
        imagen: "images/top_4disenos_1.jpg",
        imagenes: ["images/top_4disenos_1.jpg", "images/top_4disenos_2.jpg", "images/top_4disenos_3.png", "images/top_4disenos_4.jpg", "images/top_4disenos_5.jpg"],
        tallas: ["L"],
        colores: ["Leopardo", "Gris", "Rayas Blancas y Negras", "Negro Sólido"],
        estilos: ["Casual", "Verano", "Básico"],
        disponible: true,
    },
    {
        id: 16,
        nombre: "Camisetas sin mangas con bordado de lazos (🎀) - Talla L",
        categoria: "Ropa",
        subcategoria: "Camisetas",
        genero: "mujer",
        precio: 5.00,
        descripcion: "Camiseta sin mangas de escote redondo con bordado de lazo para mujeres. Disponible en 3 colores: Rosa Intenso, Rosa Claro y Blanco. Perfecta para uso casual y diario.",
        imagen: "images/camiseta_lazos_1.jpg",
        imagenes: ["images/camiseta_lazos_1.jpg", "images/camiseta_lazos_2.jpg", "images/camiseta_lazos_3.jpg", "images/camiseta_lazos_4.jpg", "images/camiseta_lazos_5.jpg"],
        tallas: ["L"],
        colores: ["Rosa Intenso", "Rosa Claro", "Blanco"],
        estilos: ["Casual", "Básico", "Diario"],
        disponible: true,
    },
    {
        id: 17,
        nombre: "Set de pijama con estampado de caricatura (🧸) - Talla L",
        categoria: "Ropa",
        subcategoria: "Pijamas",
        genero: "mujer",
        precio: 7.00,
        descripcion: "Set de Pijama con Estampado de Caricatura: Camiseta de Tirantes y Pantalones Cortos. Disponible en varios diseños adorables: Corazón, Osito, Moño y Lazos.",
        imagen: "images/pijama_caricatura_1.jpg",
        imagenes: ["images/pijama_caricatura_1.jpg", "images/pijama_caricatura_2.jpg", "images/pijama_caricatura_3.jpg", "images/pijama_caricatura_4.jpg"],
        tallas: ["L"],
        colores: ["Beige", "Rojo", "Negro", "Rosa"],
        estilos: ["Pijama", "Verano", "Cómodo"],
        disponible: true,
    },
    {
        id: 18,
        nombre: "Set de pijama con estampado de caricatura (🥑) - Talla M",
        categoria: "Ropa",
        subcategoria: "Pijamas",
        genero: "mujer",
        precio: 7.00,
        descripcion: "Set de Pijama con Estampado de Caricatura: Camiseta de Tirantes y Pantalones Cortos. Diseños divertidos: Aguacate, Osito Rosa, Leopardo y Negro 'Honey'.",
        imagen: "images/pijama_aguacate_1.jpg",
        imagenes: ["images/pijama_aguacate_1.jpg", "images/pijama_aguacate_2.jpg", "images/pijama_aguacate_3.jpg", "images/pijama_aguacate_4.jpg"],
        tallas: ["M"],
        colores: ["Blanco/Aguacate", "Negro/Osito", "Negro/Leopardo"],
        estilos: ["Pijama", "Verano", "Divertido"],
        disponible: true,
    },
    {
        id: 19,
        nombre: "Set de pijama con estampado de fresas (🍓) - Talla S",
        categoria: "Ropa",
        subcategoria: "Pijamas",
        genero: "mujer",
        precio: 7.00,
        descripcion: "Set de Pijama con Estampado de Fresas: Camiseta de Tirantes y Pantalones Cortos con lazo. Disponible en 3 colores: Negro, Rosa y Blanco.",
        imagen: "images/pijama_fresas_1.jpg",
        imagenes: ["images/pijama_fresas_1.jpg", "images/pijama_fresas_2.jpg", "images/pijama_fresas_3.jpg", "images/pijama_fresas_4.jpg"],
        tallas: ["S", "M", "L"],
        colores: ["Negro", "Rosa", "Blanco"],
        estilos: ["Pijama", "Verano", "Cute"],
        disponible: true,
    },
    {
        id: 20,
        nombre: "Set de Pijama Casual de Canalé - Talla L",
        categoria: "Ropa",
        subcategoria: "Pijamas",
        genero: "mujer",
        precio: 9.00,
        descripcion: "Set de Pijama Casual de tejido canalé (ribbed) suave. Camiseta de tirantes con detalle de lazo y pantalones cortos con borde ondulado. Disponible en Lila, Beige y Verde Menta.",
        imagen: "images/pijama_casual_1.jpg",
        imagenes: ["images/pijama_casual_1.jpg", "images/pijama_casual_2.jpg", "images/pijama_casual_3.jpg", "images/pijama_casual_4.jpg", "images/pijama_casual_5.jpg"],
        tallas: ["L"],
        colores: ["Lila", "Beige", "Verde Menta"],
        estilos: ["Casual", "Cómodo", "Básico"],
        disponible: true,
    },
    {
        id: 21,
        nombre: "Pullover con diseño de corazón/Love (🩷) - Talla M",
        categoria: "Ropa",
        subcategoria: "Tops",
        genero: "mujer",
        precio: 5.00,
        descripcion: "Pullover casual de manga corta con estampados románticos de corazón y texto 'Love'. Disponible en 3 colores: Negro, Rojo y Blanco. Tela suave y cómoda.",
        imagen: "images/pullover_love_1.png",
        imagenes: ["images/pullover_love_1.png", "images/pullover_love_2.png", "images/pullover_love_3.png", "images/pullover_love_4.png", "images/pullover_love_5.png"],
        tallas: ["M"],
        colores: ["Negro", "Rojo", "Blanco"],
        estilos: ["Casual", "Romántico", "Diario"],
        disponible: true,
    },
    {
        id: 22,
        nombre: "Set de ropa interior informal (Top Tubo + Shorts) Rojo Vino - Talla L",
        categoria: "Ropa",
        subcategoria: "Lencería",
        genero: "mujer",
        precio: 8.00,
        descripcion: "Set de dos piezas informal y cómodo. Incluye top tipo tubo sin tirantes y shorts ajustados con textura a cuadros. Ideal para estar en casa o uso casual.",
        imagen: "images/ropa_interior_informal_1.png",
        imagenes: ["images/ropa_interior_informal_1.png", "images/ropa_interior_informal_2.png", "images/ropa_interior_informal_3.jpg"],
        tallas: ["L"],
        colores: ["Rojo Vino"],
        estilos: ["Casual", "Sexy", "Cómodo"],
        disponible: true,
    },
    {
        id: 23,
        nombre: "Set de ropa interior informal (Top Tubo + Shorts) Carmelita - Talla M",
        categoria: "Ropa",
        subcategoria: "Lencería",
        genero: "mujer",
        precio: 8.00,
        descripcion: "Set de dos piezas informal y cómodo. Incluye top tipo tubo sin tirantes y shorts ajustados con textura a cuadros. Ideal para estar en casa o uso casual.",
        imagen: "images/ropa_interior_carmelita_1.png",
        imagenes: ["images/ropa_interior_carmelita_1.png", "images/ropa_interior_carmelita_2.png", "images/ropa_interior_carmelita_3.png"],
        tallas: ["M"],
        colores: ["Carmelita"],
        estilos: ["Casual", "Sexy", "Cómodo"],
        disponible: true,
    },
    {
        id: 24,
        nombre: "Set de Lencería Sexy (👙🩷) - Talla S",
        categoria: "Ropa",
        subcategoria: "Lencería",
        genero: "mujer",
        precio: 6.00,
        descripcion: "Set de lencería sexy de dos piezas en blanco con detalles de encaje rojo y estampado de corazones. Incluye sujetador y tanga a juego.",
        imagen: "images/lenceria_corazones_1.png",
        imagenes: ["images/lenceria_corazones_1.png", "images/lenceria_corazones_2.png", "images/lenceria_corazones_3.png"],
        tallas: ["S"],
        colores: ["Blanco/Rojo"],
        estilos: ["Sexy", "Romántico", "Lencería"],
        disponible: true,
    },
    {
        id: 25,
        nombre: "Set de Lencería Sexy (🐆) - Talla L",
        categoria: "Ropa",
        subcategoria: "Lencería",
        genero: "mujer",
        precio: 6.00,
        descripcion: "Set de lencería sexy de dos piezas con estampado de leopardo y detalles de encaje negro. Incluye sujetador y tanga a juego.",
        imagen: "images/lenceria_leopardo_1.png",
        imagenes: ["images/lenceria_leopardo_1.png", "images/lenceria_leopardo_2.png", "images/lenceria_leopardo_3.png"],
        tallas: ["L"],
        colores: ["Leopardo"],
        estilos: ["Sexy", "Salvaje", "Lencería"],
        disponible: true,
    },
    {
        id: 26,
        nombre: "Conjunto deportivo 'Sweet' (2 Piezas) Rojo - Talla L",
        categoria: "Ropa",
        subcategoria: "Conjuntos",
        genero: "mujer",
        precio: 10.00,
        descripcion: "Conjunto de 2 piezas: sujetador deportivo con letra estampada 'Sweet' y costuras a contraste. Alta elasticidad y muy cómodo. Ideal para entrenamiento o uso casual.",
        imagen: "images/conjunto_sweet_1.jpg",
        imagenes: ["images/conjunto_sweet_1.jpg", "images/conjunto_sweet_2.png", "images/conjunto_sweet_3.jpg", "images/conjunto_sweet_4.jpg"],
        tallas: ["L"],
        colores: ["Vino"],
        estilos: ["Deportivo", "Casual", "Cómodo"],
        disponible: true,
    },
    {
        id: 27,
        nombre: "Conjunto deportivo 'Sweet' (2 Piezas) Naranja - Talla XL",
        categoria: "Ropa",
        subcategoria: "Conjuntos",
        genero: "mujer",
        precio: 10.00,
        descripcion: "Conjunto de 2 piezas: sujetador deportivo con letra estampada 'Sweet' y costuras a contraste. Alta elasticidad y muy cómodo. Ideal para entrenamiento o uso casual.",
        imagen: "images/conjunto_sweet_naranja_1.png",
        imagenes: ["images/conjunto_sweet_naranja_1.png", "images/conjunto_sweet_naranja_2.png", "images/conjunto_sweet_naranja_3.jpg", "images/conjunto_sweet_naranja_4.png"],
        tallas: ["XL"],
        colores: ["Naranja"],
        estilos: ["Deportivo", "Casual", "Cómodo"],
        disponible: true,
    },

    // ============================
    // PREMIUM - ACCESORIOS
    // ============================
    {
        id: 28,
        nombre: "Bolso Deportivo (Negro) Unisex 40L Under Armour Storm",
        categoria: "Premium",
        subcategoria: "Bolsos",
        genero: "unisex",
        precio: 40.00,
		oldPrice: 45.00,
        descripcion: "Bolso deportivo de alta resistencia con tecnología UA Storm repelente al agua. Capacidad: 40 Libras. Dimensiones: 10.6\"Ancho x 10.1\"Alto x 21.7\"Largo. Paneles inferiores y laterales resistentes con recubrimiento PU y forro de espuma. Incluye bolsillo ventilado para ropa sucia o zapatos. Bolsillo doble para botellas de agua, puntos de sujeción webbing molle y correa de hombro ajustable.",
        imagen: "images/bolso_deportivo_2.png",
        imagenes: ["images/bolso_deportivo_2.png", "images/bolso_deportivo_1.png", "images/bolso_deportivo_3.png", "images/bolso_deportivo_4.png", "images/bolso_deportivo_5.png"],
        tallas: ["Única"],
        colores: ["Negro"],
        estilos: ["Deportivo", "Resistente", "Funcional"],
        disponible: true,
    },
    {
        id: 36,
        nombre: "Bolso Deportivo (Azul Marino) Unisex 40L Under Armour Storm",
        categoria: "Premium",
        subcategoria: "Bolsos",
        genero: "unisex",
        precio: 40.00,
		oldPrice: 45.00,
        descripcion: "Bolso deportivo Under Armour Undeniable 5.0 en color azul marino. Tecnología UA Storm repelente al agua, paneles resistentes con recubrimiento de PU, bolsillo ventilado para ropa o calzado, y correa de hombro ajustable HeatGear. Ideal para el gimnasio o viajes.",
        imagen: "images/ua_duffel_navy_2.jpg",
        imagenes: ["images/ua_duffel_navy_1.jpg", "images/ua_duffel_navy_2.jpg", "images/ua_duffel_navy_3.jpg", "images/ua_duffel_navy_4.jpg", "images/ua_duffel_navy_5.jpg"],
        tallas: ["Única"],
        colores: ["Azul Marino"],
        estilos: ["Deportivo", "Resistente", "Premium"],
        disponible: true,
    },
    {
        id: 29,
        nombre: "Conjunto Deportivo (Negro) Under Armour - Talla L",
        categoria: "Premium",
        subcategoria: "Conjuntos",
        genero: "hombre",
        precio: 65.00,
		oldPrice: 70.00,
        descripcion: "Conjunto deportivo premium de dos piezas (chaqueta y pantalón) en color negro. Diseño moderno, cómodo y de alta calidad. Ideal para entrenamiento o uso casual.",
        imagen: "images/tracksuit_black_1.png",
        imagenes: ["images/tracksuit_black_1.png", "images/tracksuit_black_2.png", "images/tracksuit_black_3.png"],
        tallas: ["M", "L", "XL"],
        colores: ["Negro"],
        estilos: ["Deportivo", "Premium", "Casual"],
        disponible: true,
    },
    {
        id: 37,
        nombre: "Conjunto de Compresión (Camuflaje) Under Armour - Talla L",
        categoria: "Premium",
        subcategoria: "Conjuntos",
        genero: "hombre",
        precio: 75.00,
		oldPrice: 80.00,
        descripcion: "Conjunto de compresión Under Armour de dos piezas (camiseta de manga larga y leggings) con estampado de camuflaje en tonos oscuros. Tecnología ColdGear para mantenerte fresco y seco. Ideal para entrenamientos intensos.",
        imagen: "images/ua_compression_camo_1.jpg",
        imagenes: ["images/ua_compression_camo_1.jpg", "images/ua_compression_camo_2.jpg", "images/ua_compression_camo_3.png", "images/ua_compression_camo_5.png", "images/ua_compression_camo_6.jpg"],
        tallas: ["M", "L", "XL"],
        colores: ["Camuflaje Negro/Gris"],
        estilos: ["Deportivo", "Compresión", "Gym"],
        disponible: true,
    },
    {
        id: 30,
        nombre: "Cartera Steve Madden (Gris Azulado)",
        categoria: "Premium",
        subcategoria: "Bolsos",
        genero: "mujer",
        precio: 45.00,
		oldPrice: 50.00,
        descripcion: "Cartera Steve Madden original en color gris azulado con textura. Diseño elegante con logo en relieve y correa ajustable. Ideal para salidas casuales o eventos.",
        imagen: "images/cartera_steve_madden_1.jpg",
        imagenes: ["images/cartera_steve_madden_1.jpg", "images/cartera_steve_madden_2.jpg", "images/cartera_steve_madden_3.jpg"],
        tallas: ["Única"],
        colores: ["Gris Azulado"],
        estilos: ["Elegante", "Casual", "Premium"],
        disponible: true,
    },
    {
        id: 31,
        nombre: "Cartera Steve Madden (Verde Menta)",
        categoria: "Premium",
        subcategoria: "Bolsos",
        genero: "mujer",
        precio: 40.00,
		oldPrice: 50.00,
        descripcion: "Cartera Steve Madden original en color verde menta. Diseño chic con logo 'SM' metálico y correa de cadena plateada. Interior forrado con logo de la marca.",
        imagen: "images/cartera_steve_madden_mint_1.jpg",
        imagenes: ["images/cartera_steve_madden_mint_1.jpg", "images/cartera_steve_madden_mint_2.jpg", "images/cartera_steve_madden_mint_3.jpg"],
        tallas: ["Única"],
        colores: ["Verde Menta"],
        estilos: ["Chic", "Verano", "Premium"],
        disponible: true,
    },
    {
        id: 32,
        nombre: "Cartera Juicy Couture (Rosa)",
        categoria: "Premium",
        subcategoria: "Bolsos",
        genero: "mujer",
        precio: 35.00,
		oldPrice: 43.00,
        descripcion: "Cartera Juicy Couture original en color rosa con estampado de logotipos en relieve. Incluye correa de hombro y cadena decorativa dorada con charms (corona, corazón, logo). Estilo Y2K.",
        imagen: "images/cartera_juicy_couture_pink_1.jpg",
        imagenes: ["images/cartera_juicy_couture_pink_1.jpg", "images/cartera_juicy_couture_pink_2.jpg", "images/cartera_juicy_couture_pink_3.jpg", "images/cartera_juicy_couture_pink_4.jpg", "images/cartera_juicy_couture_pink_5.jpg"],
        tallas: ["Única"],
        colores: ["Rosa"],
        estilos: ["Y2K", "Chic", "Premium"],
        disponible: true,
    },
    {
        id: 33,
        nombre: "Set de Colonias Aéropostale (Blizzard Blush) - 4 Piezas",
        categoria: "Premium",
        subcategoria: "Perfumes",
        genero: "mujer",
        precio: 25.00,
		oldPrice: 33.00,
        descripcion: "Set de regalo Aéropostale 'Blizzard Blush' con 4 Body Mists (100ml c/u): Marshmallow Latte, Frozen Flora, Candy Carol y Whipped Shortbread. Aromas dulces y festivos ideales para regalo.",
        imagen: "images/set_colonias_aeropostale_1.jpg",
        imagenes: ["images/set_colonias_aeropostale_1.jpg", "images/set_colonias_aeropostale_2.jpg"],
        tallas: ["4x100ml"],
        colores: ["Multicolor"],
        estilos: ["Regalo", "Dulce", "Premium"],
        disponible: true,
    },
    {
        id: 34,
        nombre: "Set de Regalo GUESS Seductive Dream (2 Piezas)",
        categoria: "Premium",
        subcategoria: "Perfumes",
        genero: "mujer",
        precio: 35.00,
		oldPrice: 43.00,
        descripcion: "Set de regalo GUESS Seductive Dream para mujer. Incluye Eau de Toilette (30ml) y Loción Corporal (100ml). Una fragancia floral y seductora en un hermoso empaque rosa.",
        imagen: "images/set_guess_seductive_dream.jpg",
        imagenes: ["images/set_guess_seductive_dream.jpg"],
        tallas: ["30ml + 100ml"],
        colores: ["Rosa"],
        estilos: ["Elegante", "Seductor", "Regalo"],
        disponible: true,
    },
    {
        id: 35,
        nombre: "Set de Regalo GUESS Seductive (2 Piezas)",
        categoria: "Premium",
        subcategoria: "Perfumes",
        genero: "mujer",
        precio: 35.00,
		oldPrice: 43.00,
        descripcion: "Set de regalo GUESS Seductive clásico para mujer. Incluye Eau de Toilette (30ml) y Loción Corporal (100ml). Una fragancia cautivadora con notas florales y amaderadas en un elegante empaque con diseño de leopardo.",
        imagen: "images/set_guess_seductive_leopard.jpg",
        imagenes: ["images/set_guess_seductive_leopard.jpg"],
        tallas: ["30ml + 100ml"],
        colores: ["Dorado/Leopardo"],
        estilos: ["Clásico", "Seductor", "Regalo"],
        disponible: true,
    },
];

