// ==============================
// CONFIGURACIÓN: TUS PRODUCTOS
// ==============================
// Modifica este array para añadir / quitar / editar productos.
// Solo tú, editando este archivo, puedes cambiar el catálogo.
const PRODUCTS = [
    // MAQUILLAJE
    {
        id: 1,
        nombre: "Labial Mate Rojo Intenso",
        categoria: "Maquillaje",
        subcategoria: "Labios",
        genero: "unisex",
        precio: 5.99,
        descripcion: "Labial líquido mate de larga duración, tono rojo intenso. Fórmula que no reseca los labios, acabado aterciopelado perfecto",
        imagen: "images/labial_rojo_1763621934449.png",
        imagenes: ["images/labial_rojo_1763621934449.png"],
        tallas: [], // N/A para maquillaje
        colores: ["Rojo Intenso", "Rosa Nude", "Coral"],
        estilos: ["Elegante", "Noche"],
        disponible: true,
    },
    {
        id: 2,
        nombre: "Base Líquida Full Cover",
        categoria: "Maquillaje",
        subcategoria: "Rostro",
        genero: "mujer",
        precio: 8.99,
        descripcion: "Base de alta cobertura, acabado natural. Varios tonos disponibles. Cobertura de larga duración, resistente al agua.",
        imagen: "images/base_liquida_1763621940256.png",
        imagenes: ["images/base_liquida_1763621940256.png"],
        tallas: [],
        colores: ["Claro", "Medio", "Oscuro"],
        estilos: ["Día", "Noche", "Natural"],
        disponible: true,
    },

    // ZAPATOS
    {
        id: 3,
        nombre: "Tenis Deportivos Blancos",
        categoria: "Zapatos",
        subcategoria: "Tenis",
        genero: "hombre",
        precio: 29.99,
        descripcion: "Tenis blancos casuales, cómodos para uso diario. Diseño clásico y versátil, suela acolchada para máximo confort.",
        imagen: "images/tenis_blancos_1763621945598.png",
        imagenes: ["images/tenis_blancos_1763621945598.png"],
        tallas: ["7", "8", "9", "10", "11", "12"],
        colores: ["Blanco", "Negro", "Gris"],
        estilos: ["Casual", "Deportivo", "Urbano"],
        disponible: true,
    },
    {
        id: 4,
        nombre: "Sandalias Elegantes Negras",
        categoria: "Zapatos",
        subcategoria: "Sandalias",
        genero: "mujer",
        precio: 39.99,
        descripcion: "Sandalias de tacón medio, perfectas para eventos. Diseño sofisticado y cómodo, tacón de 5cm.",
        imagen: "images/sandalias_negras_1763621955885.png",
        imagenes: ["images/sandalias_negras_1763621955885.png"],
        tallas: ["5", "6", "7", "8", "9"],
        colores: ["Negro", "Plateado", "Dorado"],
        estilos: ["Elegante", "Fiesta", "Formal"],
        disponible: true,
    },

    // ROPA - HOMBRE
    {
        id: 5,
        nombre: "Pullover Básico Blanco",
        categoria: "Ropa",
        subcategoria: "Pullover",
        genero: "hombre",
        precio: 9.99,
        descripcion: "Pullover de algodón 100%, cuello redondo, color blanco. Corte regular, tela suave y transpirable.",
        imagen: "images/pullover_hombre_1763621961215.png",
        imagenes: ["images/pullover_hombre_1763621961215.png"],
        tallas: ["S", "M", "L", "XL", "XXL"],
        colores: ["Blanco", "Negro", "Gris", "Azul Marino"],
        estilos: ["Casual", "Básico", "Everyday"],
        disponible: true,
    },
    {
        id: 6,
        nombre: "Pantalón Jeans Azul",
        categoria: "Ropa",
        subcategoria: "Pantalón",
        genero: "hombre",
        precio: 24.99,
        descripcion: "Jeans azul clásico, corte recto. Denim de calidad, diseño atemporal y versátil.",
        imagen: "images/jeans_hombre_1763621967388.png",
        imagenes: ["images/jeans_hombre_1763621967388.png"],
        tallas: ["28", "30", "32", "34", "36", "38"],
        colores: ["Azul", "Azul Oscuro", "Negro"],
        estilos: ["Casual", "Clásico"],
        disponible: true,
    },

    // ROPA - MUJER
    {
        id: 7,
        nombre: "Shorts de Mezclilla",
        categoria: "Ropa",
        subcategoria: "Shorts",
        genero: "mujer",
        precio: 22.99,
        descripcion: "Shorts de mezclilla, tiro alto. Perfecto para verano, diseño moderno y cómodo.",
        imagen: "images/shorts_mujer_1763621973145.png",
        imagenes: ["images/shorts_mujer_1763621973145.png"],
        tallas: ["XS", "S", "M", "L", "XL"],
        colores: ["Azul Claro", "Azul Oscuro", "Negro"],
        estilos: ["Casual", "Verano", "Moderno"],
        disponible: true,
    },
    {
        id: 8,
        nombre: "Pullover Oversize Rosa",
        categoria: "Ropa",
        subcategoria: "Pullover",
        genero: "mujer",
        precio: 17.5,
        descripcion: "Pullover oversize, color rosa pastel. Tela suave, perfecto para un look relajado.",
        imagen: "images/pullover_mujer_1763621978863.png",
        imagenes: ["images/pullover_mujer_1763621978863.png"],
        tallas: ["S", "M", "L"],
        colores: ["Rosa Pastel", "Gris", "Beige"],
        estilos: ["Casual", "Oversized", "Cómodo"],
        disponible: true,
    },
    {
        id: 9,
        nombre: "Vestido Floral Verano",
        categoria: "Ropa",
        subcategoria: "Vestidos",
        genero: "mujer",
        precio: 35.00,
        descripcion: "Vestido ligero con estampado floral, ideal para el calor. Diseño fresco y femenino.",
        imagen: "images/vestido_floral_1763621984939.png",
        imagenes: ["images/vestido_floral_1763621984939.png"],
        tallas: ["XS", "S", "M", "L", "XL"],
        colores: ["Floral Azul", "Floral Rosa", "Floral Verde"],
        estilos: ["Verano", "Romántico", "Casual"],
        disponible: true,
    },

    // ============================
    // PREMIUM - MARCAS PREMIUM
    // ============================
    {
        id: 10,
        nombre: "Pantalón Premium Diseñador",
        categoria: "Premium",
        subcategoria: "Pantalones",
        genero: "hombre",
        precio: 49.99,
        descripcion: "Pantalón de marca premium, corte perfecto y tela de alta calidad. Diseño exclusivo italiano.",
        imagen: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=400&h=300&fit=crop",
        imagenes: ["https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=400&h=300&fit=crop"],
        tallas: ["30", "32", "34", "36"],
        colores: ["Negro", "Gris Carbón", "Azul Marino"],
        estilos: ["Premium", "Formal", "Elegante"],
        disponible: true,
    },
    {
        id: 11,
        nombre: "Pullover Cashmere Lujo",
        categoria: "Premium",
        subcategoria: "Pullovers",
        genero: "mujer",
        precio: 39.99,
        descripcion: "Pullover de cashmere auténtico, suave y elegante. Fabricado en Italia, calidad excepcional.",
        imagen: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=400&h=300&fit=crop",
        imagenes: ["https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=400&h=300&fit=crop"],
        tallas: ["XS", "S", "M", "L"],
        colores: ["Beige", "Negro", "Gris"],
        estilos: ["Premium", "Elegante", "Lujo"],
        disponible: true,
    },
    {
        id: 12,
        nombre: "Shorts Premium Verano",
        categoria: "Premium",
        subcategoria: "Shorts",
        genero: "unisex",
        precio: 39.99,
        descripcion: "Shorts de marca reconocida, tela ligera y diseño exclusivo. Perfecto para cualquier ocasión.",
        imagen: "https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=400&h=300&fit=crop",
        imagenes: ["https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=400&h=300&fit=crop"],
        tallas: ["XS", "S", "M", "L", "XL"],
        colores: ["Blanco", "Negro", "Caqui"],
        estilos: ["Premium", "Verano", "Casual"],
        disponible: true,
    },
    {
        id: 13,
        nombre: "Zapatos Deportivos Premium",
        categoria: "Premium",
        subcategoria: "Zapatos",
        genero: "unisex",
        precio: 99.99,
        descripcion: "Calzado deportivo de marca premium, tecnología avanzada y estilo único. Edición limitada.",
        imagen: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=300&fit=crop",
        imagenes: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=300&fit=crop"],
        tallas: ["7", "8", "9", "10", "11", "12"],
        colores: ["Blanco/Negro", "Todo Negro", "Gris/Azul"],
        estilos: ["Premium", "Deportivo", "Sneaker"],
        disponible: true,
    },
    {
        id: 14,
        nombre: "Top sin Mangas Ajustado - 4 Diseños",
        categoria: "Ropa",
        subcategoria: "Tops",
        genero: "mujer",
        precio: 8.00,
        descripcion: "Top sin mangas ajustado y versátil, disponible en 4 diseños: negro sólido con lazo, gris, rayas blancas y negras, y blanco con estampado de cerezas. Perfecto para verano, vacaciones y la playa.",
        imagen: "images/top_rayas_3.png",
        imagenes: ["images/top_rayas_3.png", "images/top_rayas_2.png", "images/top_rayas_1.png"],
        tallas: ["L"],
        colores: ["Negro con Lazo", "Gris", "Rayas Blancas y Negras", "Blanco Cherry"],
        estilos: ["Verano", "Casual", "Playa"],
        disponible: true,
    },
];

